console.error("Help!")
console.log('tst rerun')
console.warn("fault ahead")
